export const CLASS_DEFINITIONS = {
  scholar: {
    id: "scholar",
    name: "Scholar",
    tagline: "Master knowledge through focused study.",
    tags: ["study sessions", "exam prep", "courses", "reading", "notes", "research"],
  },
  warrior: {
    id: "warrior",
    name: "Warrior",
    tagline: "Build discipline through health and routine.",
    tags: ["workout", "sleep", "nutrition", "mental health", "morning routine", "endurance"],
  },
  builder: {
    id: "builder",
    name: "Builder",
    tagline: "Ship real things and level up your craft.",
    tags: ["coding", "projects", "design", "writing", "skill building", "shipping"],
  },
  strategist: {
    id: "strategist",
    name: "Strategist",
    tagline: "Plan smart moves for long-term growth.",
    tags: ["career growth", "networking", "job search", "finance habits", "business goals", "planning"],
  },
};

export const STARTER_QUESTS = {
  scholar: [
    {
      templateKey: "scholar-focus-block",
      title: "Complete a 45-minute focused study block",
      description: "Pick one topic and study with zero distractions.",
      category: "knowledge",
      type: "daily",
      difficulty: "medium",
      priority: "high",
      tags: ["study", "focus"],
    },
    {
      templateKey: "scholar-active-recall",
      title: "Revise notes using active recall",
      description: "Review key concepts and self-test your memory.",
      category: "knowledge",
      type: "daily",
      difficulty: "easy",
      priority: "medium",
      tags: ["revision", "notes"],
    },
    {
      templateKey: "scholar-reading",
      title: "Read 15 pages of learning material",
      description: "Read a chapter, article, or concept summary and capture one key insight.",
      category: "knowledge",
      type: "daily",
      difficulty: "easy",
      priority: "medium",
      tags: ["reading", "learning"],
    },
  ],
  warrior: [
    {
      templateKey: "warrior-workout",
      title: "Complete a 30-minute workout",
      description: "Choose strength, cardio, or mobility and finish one full session.",
      category: "health",
      type: "daily",
      difficulty: "medium",
      priority: "high",
      tags: ["workout", "fitness"],
    },
    {
      templateKey: "warrior-hydration",
      title: "Hit your hydration target",
      description: "Track and complete your planned water intake for today.",
      category: "health",
      type: "daily",
      difficulty: "easy",
      priority: "medium",
      tags: ["health", "routine"],
    },
    {
      templateKey: "warrior-sleep",
      title: "Lock your sleep window",
      description: "Set and follow a fixed bedtime to support recovery.",
      category: "health",
      type: "daily",
      difficulty: "medium",
      priority: "high",
      tags: ["sleep", "recovery"],
    },
  ],
  builder: [
    {
      templateKey: "builder-deep-work",
      title: "Ship one focused build session",
      description: "Spend 60 minutes building your project without context switching.",
      category: "productivity",
      type: "daily",
      difficulty: "medium",
      priority: "high",
      tags: ["build", "deep-work"],
    },
    {
      templateKey: "builder-learning",
      title: "Learn one practical concept",
      description: "Learn and apply one concept to your current project.",
      category: "knowledge",
      type: "daily",
      difficulty: "easy",
      priority: "medium",
      tags: ["learning", "coding"],
    },
    {
      templateKey: "builder-document",
      title: "Document what you shipped today",
      description: "Write a short log of progress, blockers, and next step.",
      category: "productivity",
      type: "daily",
      difficulty: "easy",
      priority: "medium",
      tags: ["reflection", "shipping"],
    },
  ],
  strategist: [
    {
      templateKey: "strategist-plan",
      title: "Plan your top 3 strategic priorities",
      description: "Define three high-impact outcomes for today and sequence them.",
      category: "productivity",
      type: "daily",
      difficulty: "medium",
      priority: "high",
      tags: ["planning", "priorities"],
    },
    {
      templateKey: "strategist-career",
      title: "Take one career growth action",
      description: "Apply to a role, improve resume, or practice an interview topic.",
      category: "social",
      type: "daily",
      difficulty: "easy",
      priority: "medium",
      tags: ["career", "growth"],
    },
    {
      templateKey: "strategist-network",
      title: "Make one meaningful network touchpoint",
      description: "Message a mentor, peer, or recruiter with clear intent.",
      category: "social",
      type: "daily",
      difficulty: "easy",
      priority: "medium",
      tags: ["network", "communication"],
    },
  ],
};

export const RECOVERY_QUEST = {
  templateKey: "recovery-quest",
  title: "Recovery Quest: Win the day back",
  description: "Complete one meaningful task today to restore momentum.",
  category: "productivity",
  type: "daily",
  difficulty: "medium",
  priority: "high",
  tags: ["recovery", "streak", "momentum"],
};

export const DUAL_CLASS_UNLOCK_STREAK_DAYS = 60;
